name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Se ejecuta solo cuando subes cambios a la rama main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Autenticarse con Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # 2. Configurar el SDK de Google Cloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create env.yaml file
        run: |
          cd backend
          echo "${{ secrets.BACKEND_ENV_FILE }}" > env.yaml

      # 3. ->>>> Usamos archivo cloudbuild.yaml del backend
      - name: Build and Deploy Backend
        run: |
          cd backend
          gcloud builds submit --config cloudbuild.yaml .

  deploy-frontend:
    #needs: deploy-backend # Opcional: Espera a que el back termine antes de lanzar el front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 4. Usamos TU archivo cloudbuild.yaml del frontend
      - name: Build and Deploy Frontend
        run: |
          cd frontend
          gcloud builds submit --config cloudbuild.yaml .