name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'  # Solo mira cambios del backend
      - '.github/workflows/deploy-backend.yaml' # Y si cambia este archivo tambiÃ©n

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Autenticarse con Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # 2. Configurar el SDK de Google Cloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Inyectamos el env.yaml desde los secretos 
      - name: Create env.yaml
        run: |
          cd backend
          echo "${{ secrets.BACKEND_ENV_FILE }}" > env.yaml

      # 3. ->>>> Usamos archivo cloudbuild.yaml del backend
      - name: Build and Deploy
        run: |
          cd backend
          gcloud builds submit --config cloudbuild.yaml .